# Base image
FROM node:latest

# Set working directory
WORKDIR /backend

# Copy backend files
COPY . /backend/

# Install dependencies
RUN npm install 

# Expose ports
EXPOSE 5000
EXPOSE 27017

# Start the application
CMD ["npm", "start"]